function esc(s) {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function airportStatusText(varMin, slack) {
  if (varMin == null) return "Status: —";
  if (Math.abs(varMin) <= slack) return "Status: ON-TIME";
  if (varMin > 0) return `Status: +${varMin}m Delay`;
  return `Status: ${varMin}m Early`;
}

function formatActualHm(iso, timeZone) {
  if (!iso) return "—";
  try {
    return new Intl.DateTimeFormat("en-GB", {
      timeZone,
      hour: "2-digit",
      minute: "2-digit",
      hour12: false,
    }).format(new Date(iso));
  } catch {
    return String(iso).slice(11, 16);
  }
}

/**
 * Airport-style digest: Section A geofence precision, Section B safety, hub summary, footer.
 */
function buildAirportStyleDigest(rep, { brandLabel, displayTimeZone, logoUrl }) {
  const tz = displayTimeZone || "Asia/Manila";
  const slack = rep.meta?.onTimeToleranceMinutes ?? 6;
  const fs = rep.fleetStatus || {};
  const fleetLine = `ACTIVE: ${String(fs.activeGps ?? 0).padStart(2, "0")} | STATIONARY: ${String(fs.stationary ?? 0).padStart(2, "0")} | SOS: ${String(fs.sosCount ?? 0).padStart(2, "0")} | BUSES: ${fs.totalRegistered ?? "—"}`;

  const geoNote =
    rep.meta?.geofenceTerminalNote ||
    "Terminal entries reflect geofence arrivals in live dispatch (configured terminal radius, typically 500m).";

  const sectionALines = (rep.arrivalPrecision || []).map((row) => {
    const sched = row.scheduledBoard || "—";
    const actual = formatActualHm(row.geofenceArrivalAt, tz);
    const st = airportStatusText(row.varianceMinutes, slack);
    return `${row.busId} | ${row.terminal} | Scheduled: ${sched} | Actual: ${actual} | ${st}`;
  });
  const sectionAText = sectionALines.length ? sectionALines.join("\n") : "(No terminal geofence arrivals for this date.)";

  const speedRows = rep.speedViolations || [];
  const sectionBLines = speedRows.map((s) => {
    const staff = s.staff !== "—" ? s.staff : "—";
    const sp = s.speedKph != null ? `${Math.round(s.speedKph)} km/h` : "—";
    const t = s.timestamp ? String(s.timestamp).replace("T", " ").slice(0, 19) : "—";
    return `${s.busId} | ${staff} | ${sp} | ${t} | ${s.location || "—"}`;
  });
  const sectionBText = sectionBLines.length ? sectionBLines.join("\n") : "(No speed violations >80 km/h logged.)";

  const peakLines = (rep.speedingPeakByBus || []).map(
    (p) => `${p.busId} | ${p.attendantName} | Top speed ${p.topSpeedKph} km/h`
  );
  const peakText = peakLines.length ? peakLines.join("\n") : "(No speeding data.)";

  const hubLines = (rep.terminalHubs || [])
    .slice(0, 16)
    .map((h) => `${h.terminal}: ${h.tierLabel} — on-time ${h.onTime}/${h.arrivals} (${h.onTimePct}%)`);
  const hubText = hubLines.length ? hubLines.join("\n") : "(No hub aggregates.)";

  const footer =
    "This is an automated safety report generated by the Bukidnon Bus Company Command Center.";

  const text = [
    `DAILY OPERATIONAL LOG — ${brandLabel}`,
    `Report date: ${rep.reportDate}`,
    `Generated: ${rep.generatedAt}`,
    "",
    `Fleet: ${fleetLine}`,
    "",
    "SECTION A — PRECISION ACCURACY (TERMINAL GEOFENCE)",
    geoNote,
    "",
    sectionAText,
    "",
    "SECTION B — SAFETY & VIOLATIONS (TELEMETRY >80 KM/H)",
    sectionBText,
    "",
    "Peak speed by bus (attendant link):",
    peakText,
    "",
    "Terminal hub health:",
    hubText,
    "",
    footer,
  ].join("\n");

  const logoBlock = logoUrl
    ? `<img src="${esc(logoUrl)}" alt="" height="44" style="display:block;margin:0 auto 12px" />`
    : `<div style="width:52px;height:52px;margin:0 auto 12px;border-radius:12px;background:linear-gradient(135deg,#06b6d4,#0891b2);display:flex;align-items:center;justify-content:center;font-family:Segoe UI,Arial,sans-serif;font-size:20px;font-weight:800;color:#020617">BB</div>`;

  const sectionARows = (rep.arrivalPrecision || [])
    .map(
      (row) =>
        `<tr>` +
        `<td style="padding:8px 10px;border-bottom:1px solid #334155;font-family:Consolas,monospace;font-size:11px;color:#f1f5f9">${esc(row.busId)}</td>` +
        `<td style="padding:8px 10px;border-bottom:1px solid #334155;font-family:Consolas,monospace;font-size:11px;color:#e2e8f0">${esc(row.terminal)}</td>` +
        `<td style="padding:8px 10px;border-bottom:1px solid #334155;font-family:Consolas,monospace;font-size:11px;color:#cbd5e1">${esc(row.scheduledBoard || "—")}</td>` +
        `<td style="padding:8px 10px;border-bottom:1px solid #334155;font-family:Consolas,monospace;font-size:11px;color:#93c5fd">${esc(formatActualHm(row.geofenceArrivalAt, tz))}</td>` +
        `<td style="padding:8px 10px;border-bottom:1px solid #334155;font-family:Consolas,monospace;font-size:11px;color:${row.varianceMinutes != null && Math.abs(row.varianceMinutes) <= slack ? "#4ade80" : row.varianceMinutes != null && row.varianceMinutes > 0 ? "#fb923c" : "#38bdf8"}">${esc(airportStatusText(row.varianceMinutes, slack))}</td>` +
        `</tr>`
    )
    .join("");

  const sectionBRows = speedRows
    .map(
      (s) =>
        `<tr>` +
        `<td style="padding:8px 10px;border-bottom:1px solid #334155;font-family:Consolas,monospace;font-size:11px;color:#f1f5f9">${esc(s.busId)}</td>` +
        `<td style="padding:8px 10px;border-bottom:1px solid #334155;font-family:Consolas,monospace;font-size:11px;color:#e2e8f0">${esc(s.staff !== "—" ? s.staff : "—")}</td>` +
        `<td style="padding:8px 10px;border-bottom:1px solid #334155;font-family:Consolas,monospace;font-size:11px;color:#fb7185;font-weight:700">${s.speedKph != null ? esc(String(Math.round(s.speedKph))) + " km/h" : "—"}</td>` +
        `<td style="padding:8px 10px;border-bottom:1px solid #334155;font-family:Consolas,monospace;font-size:10px;color:#94a3b8">${esc(s.timestamp ? String(s.timestamp).replace("T", " ").slice(0, 19) : "—")}</td>` +
        `<td style="padding:8px 10px;border-bottom:1px solid #334155;font-family:Consolas,monospace;font-size:10px;color:#94a3b8">${esc(s.location || "—")}</td>` +
        `</tr>`
    )
    .join("");

  const peakRows = (rep.speedingPeakByBus || [])
    .map(
      (p) =>
        `<tr><td style="padding:6px 10px;border-bottom:1px solid #1e293b;font-family:Consolas,monospace;font-size:11px;color:#f1f5f9">${esc(p.busId)}</td>` +
        `<td style="padding:6px 10px;border-bottom:1px solid #1e293b;font-family:Consolas,monospace;font-size:11px;color:#cbd5e1">${esc(p.attendantName)}</td>` +
        `<td style="padding:6px 10px;border-bottom:1px solid #1e293b;font-family:Consolas,monospace;font-size:11px;color:#fca5a5">${esc(String(p.topSpeedKph))} km/h</td></tr>`
    )
    .join("");

  const hubRows = (rep.terminalHubs || [])
    .slice(0, 12)
    .map(
      (h) =>
        `<tr><td style="padding:6px 10px;border-bottom:1px solid #334155;font-family:Consolas,monospace;font-size:11px;color:#e2e8f0">${esc(h.terminal)}</td>` +
        `<td style="padding:6px 10px;border-bottom:1px solid #334155;font-family:Consolas,monospace;font-size:11px;color:#94a3b8">${esc(h.tierLabel)}</td>` +
        `<td style="padding:6px 10px;border-bottom:1px solid #334155;font-family:Consolas,monospace;font-size:11px;color:#cbd5e1">${h.onTime}/${h.arrivals} (${h.onTimePct}%)</td></tr>`
    )
    .join("");

  const html = `
<table width="100%" cellpadding="0" cellspacing="0" style="background:#020617;padding:0;margin:0">
<tr><td align="center" style="padding:20px 12px">
  <table width="100%" style="max-width:720px;border-collapse:collapse;background:#020617">
    <tr><td style="background:linear-gradient(180deg,#0f172a 0%,#020617 100%);border:1px solid #1e293b;border-radius:14px;padding:20px 22px 8px">
      ${logoBlock}
      <p style="margin:0 0 4px;font-size:10px;letter-spacing:0.2em;color:#22d3ee;text-transform:uppercase;text-align:center">Command center</p>
      <h1 style="margin:0 0 10px;font-size:20px;font-weight:800;color:#f8fafc;text-align:center;letter-spacing:0.06em">Daily operational log</h1>
      <p style="margin:0;font-family:Consolas,monospace;font-size:12px;color:#94a3b8;text-align:center">${esc(brandLabel)} · ${esc(rep.reportDate)}</p>
      <p style="margin:10px 0 0;font-family:Consolas,monospace;font-size:11px;color:#64748b;text-align:center">${esc(rep.generatedAt)} UTC</p>
    </td></tr>
    <tr><td style="height:12px"></td></tr>
    <tr><td style="background:#0f172a;border:1px solid #1e293b;border-radius:12px;padding:14px 16px">
      <p style="margin:0 0 6px;font-size:9px;letter-spacing:0.14em;color:#64748b;text-transform:uppercase">Fleet status</p>
      <p style="margin:0;font-family:Consolas,monospace;font-size:13px;color:#34d399">${esc(fleetLine)}</p>
    </td></tr>
    <tr><td style="height:14px"></td></tr>
    <tr><td style="background:#0f172a;border:1px solid #1e293b;border-radius:12px;padding:16px">
      <h2 style="margin:0 0 8px;font-size:11px;letter-spacing:0.16em;color:#22d3ee;text-transform:uppercase">Section A — Precision accuracy</h2>
      <p style="margin:0 0 12px;font-size:11px;color:#94a3b8;line-height:1.45">${esc(geoNote)}</p>
      <table width="100%" style="border-collapse:collapse;background:#020617;border-radius:8px;overflow:hidden">
        <thead><tr style="background:#1e293b">
          <th align="left" style="padding:8px 10px;font-size:9px;color:#64748b;text-transform:uppercase;letter-spacing:0.08em">Bus</th>
          <th align="left" style="padding:8px 10px;font-size:9px;color:#64748b;text-transform:uppercase">Terminal</th>
          <th align="left" style="padding:8px 10px;font-size:9px;color:#64748b;text-transform:uppercase">Sched</th>
          <th align="left" style="padding:8px 10px;font-size:9px;color:#64748b;text-transform:uppercase">Actual</th>
          <th align="left" style="padding:8px 10px;font-size:9px;color:#64748b;text-transform:uppercase">Airport Δ</th>
        </tr></thead>
        <tbody>${sectionARows || `<tr><td colspan="5" style="padding:12px;color:#64748b;font-size:12px">No geofence arrivals</td></tr>`}</tbody>
      </table>
    </td></tr>
    <tr><td style="height:14px"></td></tr>
    <tr><td style="background:#0f172a;border:1px solid #1e293b;border-radius:12px;padding:16px">
      <h2 style="margin:0 0 12px;font-size:11px;letter-spacing:0.16em;color:#22d3ee;text-transform:uppercase">Section B — Safety &amp; violations</h2>
      <p style="margin:0 0 10px;font-size:11px;color:#94a3b8">Every logged instance over 80 km/h (attendant from device / assignment).</p>
      <table width="100%" style="border-collapse:collapse;background:#020617;border-radius:8px;overflow:hidden">
        <thead><tr style="background:#1e293b">
          <th align="left" style="padding:8px 10px;font-size:9px;color:#64748b;text-transform:uppercase">Bus</th>
          <th align="left" style="padding:8px 10px;font-size:9px;color:#64748b;text-transform:uppercase">Attendant</th>
          <th align="left" style="padding:8px 10px;font-size:9px;color:#64748b;text-transform:uppercase">Speed</th>
          <th align="left" style="padding:8px 10px;font-size:9px;color:#64748b;text-transform:uppercase">Time UTC</th>
          <th align="left" style="padding:8px 10px;font-size:9px;color:#64748b;text-transform:uppercase">Location</th>
        </tr></thead>
        <tbody>${sectionBRows || `<tr><td colspan="5" style="padding:12px;color:#64748b;font-size:12px">No violations</td></tr>`}</tbody>
      </table>
      <p style="margin:14px 0 6px;font-size:10px;color:#64748b;text-transform:uppercase;letter-spacing:0.1em">Peak speed by bus</p>
      <table width="100%" style="border-collapse:collapse">
        <tbody>${peakRows || `<tr><td style="padding:8px;color:#64748b">—</td></tr>`}</tbody>
      </table>
    </td></tr>
    <tr><td style="height:14px"></td></tr>
    <tr><td style="background:#0f172a;border:1px solid #1e293b;border-radius:12px;padding:14px 16px">
      <h2 style="margin:0 0 8px;font-size:11px;letter-spacing:0.14em;color:#38bdf8;text-transform:uppercase">Terminal hub health</h2>
      <table width="100%" style="border-collapse:collapse">${hubRows || `<tr><td style="color:#64748b;font-size:12px">No data</td></tr>`}</table>
    </td></tr>
    <tr><td style="padding:18px 8px 8px">
      <p style="margin:0;font-size:11px;color:#64748b;text-align:center;line-height:1.5">${esc(footer)}</p>
      <p style="margin:10px 0 0;font-size:10px;color:#475569;text-align:center">Snapshots: Admin → Reports → Archive · JSON/PDF on server if configured.</p>
    </td></tr>
  </table>
</td></tr>
</table>`;

  return { text, html, footer };
}

module.exports = { buildAirportStyleDigest, esc };
