const PDFDocument = require("pdfkit");

function airportLinePdf(row, slackMin, tz) {
  const sched = row.scheduledBoard || "—";
  const actual = row.geofenceArrivalAt
    ? new Intl.DateTimeFormat("en-GB", {
        timeZone: tz,
        hour: "2-digit",
        minute: "2-digit",
        hour12: false,
      }).format(new Date(row.geofenceArrivalAt))
    : "—";
  const st = airportStatusText(row.varianceMinutes, slackMin);
  return `${row.busId} | ${row.terminal} | Scheduled: ${sched} | Actual: ${actual} | ${st}`;
}

function airportStatusText(varMin, slack) {
  if (varMin == null) return "Status: —";
  if (Math.abs(varMin) <= slack) return "Status: ON-TIME";
  if (varMin > 0) return `Status: +${varMin}m Delay`;
  return `Status: ${varMin}m Early`;
}

/** @param {Record<string, unknown>} rep Report payload from buildDailyOperationsReport */
function renderDailyOpsPdfBuffer(rep, { brandLabel, displayTimeZone }) {
  const tz = displayTimeZone || "Asia/Manila";
  const slack = rep.meta?.onTimeToleranceMinutes ?? 6;

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      margin: 44,
      size: "LETTER",
      info: {
        Title: `Daily operational log ${rep.reportDate}`,
        Author: brandLabel,
      },
    });
    const chunks = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fillColor("#06b6d4").fontSize(18).text("Daily operational log", { align: "center" });
    doc.moveDown(0.2);
    doc.fillColor("#475569").fontSize(11).text(brandLabel, { align: "center" });
    doc.moveDown(0.4);
    doc
      .fillColor("#0f172a")
      .fontSize(9)
      .text(`Report date: ${rep.reportDate}  ·  Generated (UTC): ${rep.generatedAt}`, { align: "center" });
    doc.moveDown(0.6);

    const fs = rep.fleetStatus || {};
    doc
      .fillColor("#0f172a")
      .fontSize(10)
      .text(
        `Fleet: ACTIVE ${fs.activeGps ?? 0} | STATIONARY ${fs.stationary ?? 0} | SOS ${fs.sosCount ?? 0} | Registered buses ${fs.totalRegistered ?? "—"}`,
        { align: "center" }
      );
    doc.moveDown(1);

    doc.fillColor("#0284c7").fontSize(11).text("Section A — Precision accuracy (terminal geofence arrivals)", { underline: true });
    doc.moveDown(0.25);
    doc.fillColor("#64748b").fontSize(8).text(rep.meta?.geofenceTerminalNote || "", { width: 520 });
    doc.moveDown(0.35);
    doc.fillColor("#0f172a").font("Courier", 8);
    const arrivals = rep.arrivalPrecision || [];
    if (!arrivals.length) {
      doc.text("No terminal geofence arrivals for this date.", { width: 520 });
    } else {
      for (const row of arrivals) {
        doc.text(airportLinePdf(row, slack, tz), { width: 520 });
      }
    }
    doc.moveDown(0.8);

    doc.font("Helvetica").fillColor("#0284c7").fontSize(11).text("Section B — Safety & violations (>80 km/h)", { underline: true });
    doc.moveDown(0.35);
    doc.fillColor("#0f172a").font("Courier", 8);
    const speeds = rep.speedViolations || [];
    if (!speeds.length) {
      doc.text("No speed violations logged for this date.", { width: 520 });
    } else {
      doc.text("Bus ID | Attendant | Speed | Time (UTC) | Location", { width: 520 });
      for (const s of speeds) {
        const staff = s.staff !== "—" ? s.staff : "—";
        const sp = s.speedKph != null ? `${Math.round(s.speedKph)} km/h` : "—";
        const t = s.timestamp ? String(s.timestamp).replace("T", " ").slice(0, 19) : "—";
        doc.text(`${s.busId} | ${staff} | ${sp} | ${t} | ${s.location || "—"}`, { width: 520 });
      }
    }
    doc.moveDown(0.8);

    doc.font("Helvetica").fillColor("#334155").fontSize(8).text("Peak speed by bus (summary):", { width: 520 });
    doc.font("Courier", 8).fillColor("#0f172a");
    const peaks = rep.speedingPeakByBus || [];
    if (!peaks.length) {
      doc.text("—", { width: 520 });
    } else {
      for (const p of peaks) {
        doc.text(`${p.busId} | ${p.attendantName} | Top ${p.topSpeedKph} km/h`, { width: 520 });
      }
    }

    doc.moveDown(1);
    doc
      .font("Helvetica")
      .fillColor("#64748b")
      .fontSize(8)
      .text(
        "This is an automated safety report generated by the Bukidnon Bus Company Command Center.",
        { align: "center", width: 520 }
      );

    doc.end();
  });
}

module.exports = { renderDailyOpsPdfBuffer, airportLinePdf, airportStatusText };
